name: chatty
description: A chat app Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.1
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_core : ^0.5.0
  flare_flutter: ^2.0.6
  shared_preferences: ^0.5.10
  provider: ^4.3.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Athene
      fonts:
        - asset: fonts/Athene.otf
          style: normal
    - family: ProductSans
      fonts:
        - asset: fonts/product_sans_regular.ttf
        - asset: fonts/product_sans_bold.ttf
          style: normal
